/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './index.html',
    './js/**/*.js',
    './styles/**/*.css',
  ],
  safelist: [
    'bg-black',
    'text-white',
    'bg-gray-900',
    'text-cyan-500',
    'text-blue-600',
    'text-blue-700',
    'bg-black/70',
    'shadow-[0_0_20px_rgba(0,255,255,0.5)]',
    'shadow-[0_4px_15px_rgba(0,123,255,0.4)]',
    'text-5xl',
    'mb-4',
    'text-2xl',
    'mb-8',
    'px-8',
    'py-3',
    'text-xl',
    'border-none',
    'rounded-lg',
    'cursor-pointer',
    'transition-all',
    'duration-300',
    'translate-y-[-2px]',
    'translate-y-0',
    'z-[1]',
    'z-10',
    'min-h-screen',
    'm-0',
    'overflow-hidden',
    'flex',
    'justify-center',
    'items-center',
    'absolute',
    'inset-0',
    'flex-col',
    'rounded-xl',
    'top-5',
    'left-5',
    'hidden',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      colors: {
        cyan: {
          500: '#00ffff', // Explicitly define cyan-500
        },
      },
    },
  },
  plugins: [],
}