/**
 * @fileoverview Game mechanics and rendering constants.
 * Consolidates magic numbers from game logic, rendering, and entity systems.
 */

// HUD and Rendering Constants
export const HUD_CONSTANTS = {
  SCORE_X: 20,
  SCORE_Y: 40,
  LEVEL_Y: 70,
  LIVES_Y: 100,
  POWERUP_START_Y: 120,
  POWERUP_LINE_HEIGHT: 24,
  GLOBAL_ALPHA: 1.0,
  TEXT_ALIGN: 'left',
  FILL_STYLE: 'white',
  SHIELD_STROKE_STYLE: '#00ffff',
  SHIELD_LINE_WIDTH: 3,
  SHIELD_SHADOW_COLOR: '#0ff',
  SHIELD_SHADOW_BLUR: 20,
  PLAYER_STROKE_STYLE: '#00ffff',
  PLAYER_LINE_WIDTH: 2
};

// Player Constants
export const PLAYER_CONSTANTS = {
  INITIAL_X: 380,
  INITIAL_Y: 500,
  WIDTH: 30,
  HEIGHT: 45,
  SPEED: 7,
  NARROW_FACTOR: 0.3,
  ENGINE_TOP_WIDTH_FACTOR: 0.2,
  ENGINE_BOTTOM_WIDTH_FACTOR: 0.07,
  ENGINE_HEIGHT_FACTOR: 0.3,
  ENGINE_Y_FACTOR: 0.75,
  PULSE_SPEED_DIVISOR: 500,
  FLAME_OFFSET: 5,
  FLAME_RADIUS_FACTOR: 0.6,
  FLAME_HEIGHT_FACTOR: 3,
  DOUBLE_BLASTER_OFFSET: 0.25,
  SINGLE_BLASTER_OFFSET: 0.5
};

// Bullet Constants
export const BULLET_CONSTANTS = {
  RADIUS: 3,
  SPRITE_SIZE: 6, // radius * 2
  MOBILE_FIRE_DELAY: 400, // ms
  DESKTOP_FIRE_DELAY: 30, // ms
  FIRE_SOUND_COOLDOWN: 30 // ms
};

// Asteroid Constants
export const ASTEROID_CONSTANTS = {
  MOBILE_OBSTACLE_CAP: 14,
  MAX_OBSTACLE_RADIUS: 50,
  SEARCH_RADIUS_FALLBACK: 100,
  FRAGMENT_SPEED_MULTIPLIER: 0.3,
  FRAGMENT_SCATTER_SPEED_MIN: 0.3,
  FRAGMENT_SCATTER_SPEED_MAX: 2.5,
  FRAGMENT_BONUS_SCORE: 150,
  FRAGMENT_BONUS_Y_OFFSET: -10,
  FRAGMENT_BONUS_COLOR: '#00ff00'
};

// Starfield Constants
export const STARFIELD_CONSTANTS = {
  MOBILE_STAR_COUNT: 40,
  DESKTOP_STAR_COUNT: 100,
  STAR_SIZE_MIN: 1,
  STAR_SIZE_MAX: 3, // random * 2 + 1
  STAR_SPEED_MIN: 0.1,
  STAR_SPEED_MAX: 0.6 // random * 0.5 + 0.1
};

// Game Flow Constants
export const GAME_FLOW_CONSTANTS = {
  ASTEROIDS_PER_LEVEL: 20,
  LEVEL_CLEAR_DELAY: 1500, // ms
  MAX_WAIT_TIME: 5000, // ms
  MAX_DELTA_TIME: 250, // ms - prevent spiral of death
  MOBILE_TIME_STEP: 1000 / 30, // ms - lower FPS on mobile
  SKIP_RENDER_THRESHOLD: 3 // frames
};

// Powerup Constants
export const POWERUP_CONSTANTS = {
  MOBILE_SIZE: 40,
  DESKTOP_SIZE: 50,
  SPAWN_Y_OFFSET: -1, // -powerupSize
  FALL_SPEED: 1.5,
  PULSE_DIVISOR: 600,
  PULSE_AMPLITUDE: 0.5,
  PULSE_BASE: 0.75,
  SHIELD_SCORE_OFFSET: -20,
  SHIELD_SCORE_COLOR: '#00ffff',
  POWERUP_SCORE_OFFSET: -20,
  POWERUP_SCORE_COLOR: '#00ffff'
};

// Input Constants
export const INPUT_CONSTANTS = {
  FIRE_COOLDOWN_MS: 150,
  PAUSE_LOCK_DURATION: 300, // ms
  MOUSE_BUTTON_PRIMARY: 0,
  FIRE_LOOP_INTERVAL: 100, // ms
  MOBILE_FIRE_COOLDOWN: 250, // ms
  DESKTOP_FIRE_COOLDOWN: 150 // ms
};

// Collision Constants
export const COLLISION_CONSTANTS = {
  SPATIAL_GRID_CELL_SIZE: 60,
  MAX_OBSTACLE_RADIUS: 50 // Safe upper bound for optimization
};

// Animation Constants
export const ANIMATION_CONSTANTS = {
  SCORE_POPUP_FALL_SPEED: 0.5,
  SCORE_POPUP_FADE_SPEED: 0.02,
  ENGINE_PULSE_SPEED: 500,
  ENGINE_PULSE_AMPLITUDE: 0.5,
  ENGINE_PULSE_BASE: 0.75,
  SHIELD_PULSE_AMPLITUDE: 0.5,
  SHIELD_PULSE_BASE: 0.75
};

// Game State Constants
export const GAME_STATE_CONSTANTS = {
  INITIAL_LIVES: 3,
  INITIAL_SCORE: 0,
  INITIAL_LEVEL: 0,
  PLAYER_RESET_Y_OFFSET: 50
};

// Canvas Constants
export const CANVAS_RENDER_CONSTANTS = {
  CLEAR_RECT_ALPHA: 1.0,
  DEFAULT_STROKE_STYLE: '#ff4500',
  DEFAULT_LINE_WIDTH: 2
};

// Mobile Detection Constants
export const MOBILE_DETECTION_CONSTANTS = {
  MAX_TOUCH_POINTS: 0,
  TOUCH_EVENT: 'ontouchstart'
};