import type { HudTextAlign, ReadonlyConfig } from '@types';

/**
 * @internal
 */
type HudConstants = {
  SCORE_X: number;
  SCORE_Y: number;
  LEVEL_Y: number;
  LIVES_Y: number;
  POWERUP_START_Y: number;
  POWERUP_LINE_HEIGHT: number;
  GLOBAL_ALPHA: number;
  TEXT_ALIGN: HudTextAlign;
  FILL_STYLE: string;
  SHIELD_STROKE_STYLE: string;
  SHIELD_LINE_WIDTH: number;
  SHIELD_SHADOW_COLOR: string;
  SHIELD_SHADOW_BLUR: number;
  PLAYER_STROKE_STYLE: string;
  PLAYER_LINE_WIDTH: number;
};

export const HUD_CONSTANTS: ReadonlyConfig<HudConstants> = {
  SCORE_X: 20,
  SCORE_Y: 40,
  LEVEL_Y: 70,
  LIVES_Y: 100,
  POWERUP_START_Y: 130, // Consistent 30px spacing from Lives
  POWERUP_LINE_HEIGHT: 30, // Match spacing between other HUD elements
  GLOBAL_ALPHA: 1.0,
  TEXT_ALIGN: 'left',
  FILL_STYLE: 'white',
  SHIELD_STROKE_STYLE: '#00ffff',
  SHIELD_LINE_WIDTH: 3,
  SHIELD_SHADOW_COLOR: '#0ff',
  SHIELD_SHADOW_BLUR: 20,
  PLAYER_STROKE_STYLE: '#00ffff',
  PLAYER_LINE_WIDTH: 2,
};

export const PLAYER_CONSTANTS: ReadonlyConfig<{
  INITIAL_X: 380;
  INITIAL_Y: 500;
  WIDTH: 30;
  HEIGHT: 45;
  SPEED: 7;
  NARROW_FACTOR: 0.3;
  ENGINE_TOP_WIDTH_FACTOR: 0.2;
  ENGINE_BOTTOM_WIDTH_FACTOR: 0.07;
  ENGINE_HEIGHT_FACTOR: 0.3;
  ENGINE_Y_FACTOR: 0.75;
  PULSE_SPEED_DIVISOR: 500;
  FLAME_OFFSET: 5;
  FLAME_RADIUS_FACTOR: 0.6;
  FLAME_HEIGHT_FACTOR: 3;
  DOUBLE_BLASTER_OFFSET: 0.25;
  SINGLE_BLASTER_OFFSET: 0.5;
  SHIELD_RADIUS_FACTOR: 0.8;
}> = {
  INITIAL_X: 380,
  INITIAL_Y: 500,
  WIDTH: 30,
  HEIGHT: 45,
  SPEED: 7,
  NARROW_FACTOR: 0.3,
  ENGINE_TOP_WIDTH_FACTOR: 0.2,
  ENGINE_BOTTOM_WIDTH_FACTOR: 0.07,
  ENGINE_HEIGHT_FACTOR: 0.3,
  ENGINE_Y_FACTOR: 0.75,
  PULSE_SPEED_DIVISOR: 500,
  FLAME_OFFSET: 5,
  FLAME_RADIUS_FACTOR: 0.6,
  FLAME_HEIGHT_FACTOR: 3,
  DOUBLE_BLASTER_OFFSET: 0.25,
  SINGLE_BLASTER_OFFSET: 0.5,
  SHIELD_RADIUS_FACTOR: 0.8,
};

export const ANIMATION_CONSTANTS: ReadonlyConfig<{
  SCORE_POPUP_FALL_SPEED: number;
  SCORE_POPUP_FADE_SPEED: number;
  ENGINE_PULSE_SPEED: number;
  ENGINE_PULSE_AMPLITUDE: number;
  ENGINE_PULSE_BASE: number;
  SHIELD_PULSE_AMPLITUDE: number;
  SHIELD_PULSE_BASE: number;
}> = {
  SCORE_POPUP_FALL_SPEED: 0.5,
  SCORE_POPUP_FADE_SPEED: 0.02,
  ENGINE_PULSE_SPEED: 500,
  ENGINE_PULSE_AMPLITUDE: 0.5,
  ENGINE_PULSE_BASE: 0.75,
  SHIELD_PULSE_AMPLITUDE: 0.5,
  SHIELD_PULSE_BASE: 0.75,
};

export const GAME_STATE_CONSTANTS: ReadonlyConfig<{
  INITIAL_LIVES: number;
  INITIAL_SCORE: number;
  INITIAL_LEVEL: number;
  PLAYER_RESET_Y_OFFSET: number;
}> = {
  INITIAL_LIVES: 3,
  INITIAL_SCORE: 0,
  INITIAL_LEVEL: 0,
  PLAYER_RESET_Y_OFFSET: 50,
};

export const DEV_CONFIG = {
  DEBUG_MODE: false, // Enable runtime assertions and profiling
  SHOW_PERFORMANCE_METRICS: false, // Show performance HUD
} as const;
