import type { HudTextAlign, ReadonlyConfig } from '@types';

type HudConstants = {
  SCORE_X: number;
  SCORE_Y: number;
  LEVEL_Y: number;
  LIVES_Y: number;
  POWERUP_START_Y: number;
  POWERUP_LINE_HEIGHT: number;
  GLOBAL_ALPHA: number;
  TEXT_ALIGN: HudTextAlign;
  FILL_STYLE: string;
  SHIELD_STROKE_STYLE: string;
  SHIELD_LINE_WIDTH: number;
  SHIELD_SHADOW_COLOR: string;
  SHIELD_SHADOW_BLUR: number;
  PLAYER_STROKE_STYLE: string;
  PLAYER_LINE_WIDTH: number;
};

export const HUD_CONSTANTS: ReadonlyConfig<HudConstants> = {
  SCORE_X: 20,
  SCORE_Y: 40,
  LEVEL_Y: 70,
  LIVES_Y: 100,
  POWERUP_START_Y: 120,
  POWERUP_LINE_HEIGHT: 24,
  GLOBAL_ALPHA: 1.0,
  TEXT_ALIGN: 'left',
  FILL_STYLE: 'white',
  SHIELD_STROKE_STYLE: '#00ffff',
  SHIELD_LINE_WIDTH: 3,
  SHIELD_SHADOW_COLOR: '#0ff',
  SHIELD_SHADOW_BLUR: 20,
  PLAYER_STROKE_STYLE: '#00ffff',
  PLAYER_LINE_WIDTH: 2,
};

export const PLAYER_CONSTANTS: ReadonlyConfig<{
  INITIAL_X: 380,
  INITIAL_Y: 500,
  WIDTH: 30,
  HEIGHT: 45,
  SPEED: 7,
  NARROW_FACTOR: 0.3,
  ENGINE_TOP_WIDTH_FACTOR: 0.2,
  ENGINE_BOTTOM_WIDTH_FACTOR: 0.07,
  ENGINE_HEIGHT_FACTOR: 0.3,
  ENGINE_Y_FACTOR: 0.75,
  PULSE_SPEED_DIVISOR: 500,
  FLAME_OFFSET: 5,
  FLAME_RADIUS_FACTOR: 0.6,
  FLAME_HEIGHT_FACTOR: 3,
  DOUBLE_BLASTER_OFFSET: 0.25,
  SINGLE_BLASTER_OFFSET: 0.5,
  SHIELD_RADIUS_FACTOR: 0.8,
}> = {
  INITIAL_X: 380,
  INITIAL_Y: 500,
  WIDTH: 30,
  HEIGHT: 45,
  SPEED: 7,
  NARROW_FACTOR: 0.3,
  ENGINE_TOP_WIDTH_FACTOR: 0.2,
  ENGINE_BOTTOM_WIDTH_FACTOR: 0.07,
  ENGINE_HEIGHT_FACTOR: 0.3,
  ENGINE_Y_FACTOR: 0.75,
  PULSE_SPEED_DIVISOR: 500,
  FLAME_OFFSET: 5,
  FLAME_RADIUS_FACTOR: 0.6,
  FLAME_HEIGHT_FACTOR: 3,
  DOUBLE_BLASTER_OFFSET: 0.25,
  SINGLE_BLASTER_OFFSET: 0.5,
  SHIELD_RADIUS_FACTOR: 0.8,
};

export const BULLET_CONSTANTS: ReadonlyConfig<{
  RADIUS: number;
  SPRITE_SIZE: number;
  MOBILE_FIRE_DELAY: number;
  DESKTOP_FIRE_DELAY: number;
  FIRE_SOUND_COOLDOWN: number;
}> = {
  RADIUS: 3,
  SPRITE_SIZE: 6, // radius * 2
  MOBILE_FIRE_DELAY: 400, // ms
  DESKTOP_FIRE_DELAY: 30, // ms
  FIRE_SOUND_COOLDOWN: 30, // ms
};

export const ASTEROID_CONSTANTS: ReadonlyConfig<{
  MOBILE_OBSTACLE_CAP: number;
  MAX_OBSTACLE_RADIUS: number;
  SEARCH_RADIUS_FALLBACK: number;
  FRAGMENT_SPEED_MULTIPLIER: number;
  FRAGMENT_SCATTER_SPEED_MIN: number;
  FRAGMENT_SCATTER_SPEED_MAX: number;
  FRAGMENT_BONUS_SCORE: number;
  FRAGMENT_BONUS_Y_OFFSET: number;
  FRAGMENT_BONUS_COLOR: string;
}> = {
  MOBILE_OBSTACLE_CAP: 14,
  MAX_OBSTACLE_RADIUS: 50,
  SEARCH_RADIUS_FALLBACK: 100,
  FRAGMENT_SPEED_MULTIPLIER: 0.3,
  FRAGMENT_SCATTER_SPEED_MIN: 0.3,
  FRAGMENT_SCATTER_SPEED_MAX: 2.5,
  FRAGMENT_BONUS_SCORE: 150,
  FRAGMENT_BONUS_Y_OFFSET: -10,
  FRAGMENT_BONUS_COLOR: '#00ff00',
};

export const STARFIELD_CONSTANTS: ReadonlyConfig<{
  MOBILE_STAR_COUNT: number;
  DESKTOP_STAR_COUNT: number;
  STAR_SIZE_MIN: number;
  STAR_SIZE_MAX: number;
  STAR_SPEED_MIN: number;
  STAR_SPEED_MAX: number;
}> = {
  MOBILE_STAR_COUNT: 40,
  DESKTOP_STAR_COUNT: 100,
  STAR_SIZE_MIN: 1,
  STAR_SIZE_MAX: 3, // random * 2 + 1
  STAR_SPEED_MIN: 0.1,
  STAR_SPEED_MAX: 0.6, // random * 0.5 + 0.1
};

export const GAME_FLOW_CONSTANTS: ReadonlyConfig<{
  ASTEROIDS_PER_LEVEL: number;
  LEVEL_CLEAR_DELAY: number;
  MAX_WAIT_TIME: number;
  MAX_DELTA_TIME: number;
  MOBILE_TIME_STEP: number;
  SKIP_RENDER_THRESHOLD: number;
}> = {
  ASTEROIDS_PER_LEVEL: 20,
  LEVEL_CLEAR_DELAY: 1500, // ms
  MAX_WAIT_TIME: 5000, // ms
  MAX_DELTA_TIME: 250, // ms - prevent spiral of death
  MOBILE_TIME_STEP: 1000 / 30, // ms - lower FPS on mobile
  SKIP_RENDER_THRESHOLD: 3, // frames
};

export const POWERUP_CONSTANTS: ReadonlyConfig<{
  MOBILE_SIZE: number;
  DESKTOP_SIZE: number;
  SPAWN_Y_OFFSET: number;
  FALL_SPEED: number;
  PULSE_DIVISOR: number;
  PULSE_AMPLITUDE: number;
  PULSE_BASE: number;
  SHIELD_SCORE_OFFSET: number;
  SHIELD_SCORE_COLOR: string;
  POWERUP_SCORE_OFFSET: number;
  POWERUP_SCORE_COLOR: string;
}> = {
  MOBILE_SIZE: 40,
  DESKTOP_SIZE: 50,
  SPAWN_Y_OFFSET: -1, // -powerupSize
  FALL_SPEED: 1.5,
  PULSE_DIVISOR: 600,
  PULSE_AMPLITUDE: 0.5,
  PULSE_BASE: 0.75,
  SHIELD_SCORE_OFFSET: -20,
  SHIELD_SCORE_COLOR: '#00ffff',
  POWERUP_SCORE_OFFSET: -20,
  POWERUP_SCORE_COLOR: '#00ffff',
};

export const INPUT_CONSTANTS: ReadonlyConfig<{
  FIRE_COOLDOWN_MS: number;
  PAUSE_LOCK_DURATION: number;
  MOUSE_BUTTON_PRIMARY: number;
  FIRE_LOOP_INTERVAL: number;
  MOBILE_FIRE_COOLDOWN: number;
  DESKTOP_FIRE_COOLDOWN: number;
}> = {
  FIRE_COOLDOWN_MS: 150,
  PAUSE_LOCK_DURATION: 300, // ms
  MOUSE_BUTTON_PRIMARY: 0,
  FIRE_LOOP_INTERVAL: 100, // ms
  MOBILE_FIRE_COOLDOWN: 250, // ms
  DESKTOP_FIRE_COOLDOWN: 150, // ms
};

export const COLLISION_CONSTANTS: ReadonlyConfig<{
  SPATIAL_GRID_CELL_SIZE: number;
  MAX_OBSTACLE_RADIUS: number;
}> = {
  SPATIAL_GRID_CELL_SIZE: 60,
  MAX_OBSTACLE_RADIUS: 50, // Safe upper bound for optimization
};

export const ANIMATION_CONSTANTS: ReadonlyConfig<{
  SCORE_POPUP_FALL_SPEED: number;
  SCORE_POPUP_FADE_SPEED: number;
  ENGINE_PULSE_SPEED: number;
  ENGINE_PULSE_AMPLITUDE: number;
  ENGINE_PULSE_BASE: number;
  SHIELD_PULSE_AMPLITUDE: number;
  SHIELD_PULSE_BASE: number;
}> = {
  SCORE_POPUP_FALL_SPEED: 0.5,
  SCORE_POPUP_FADE_SPEED: 0.02,
  ENGINE_PULSE_SPEED: 500,
  ENGINE_PULSE_AMPLITUDE: 0.5,
  ENGINE_PULSE_BASE: 0.75,
  SHIELD_PULSE_AMPLITUDE: 0.5,
  SHIELD_PULSE_BASE: 0.75,
};

export const GAME_STATE_CONSTANTS: ReadonlyConfig<{
  INITIAL_LIVES: number;
  INITIAL_SCORE: number;
  INITIAL_LEVEL: number;
  PLAYER_RESET_Y_OFFSET: number;
}> = {
  INITIAL_LIVES: 3,
  INITIAL_SCORE: 0,
  INITIAL_LEVEL: 0,
  PLAYER_RESET_Y_OFFSET: 50,
};

export const CANVAS_RENDER_CONSTANTS: ReadonlyConfig<{
  CLEAR_RECT_ALPHA: number;
  DEFAULT_STROKE_STYLE: string;
  DEFAULT_LINE_WIDTH: number;
}> = {
  CLEAR_RECT_ALPHA: 1.0,
  DEFAULT_STROKE_STYLE: '#ff4500',
  DEFAULT_LINE_WIDTH: 2,
};

export const MOBILE_DETECTION_CONSTANTS: ReadonlyConfig<{
  MAX_TOUCH_POINTS: number;
  TOUCH_EVENT: string;
}> = {
  MAX_TOUCH_POINTS: 0,
  TOUCH_EVENT: 'ontouchstart',
};
